apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infrion-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: infrion.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: infrion-service
            port:
              number: 80
